import { Inter } from "next/font/google";
import { ClerkProvider } from "@clerk/nextjs";
import "./globals.css";
import Navbar from "@/component/Navbar";
import SessionLayout from "./(layout)/SessionLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    // <ClerkProvider>
    <SessionLayout>
      <html lang="en">
        <body>
          {/* <Navbar /> */}
          <section className="min-h-screen">{children}</section>
        </body>
      </html>
    </SessionLayout>
    // </ClerkProvider>
  );
}
